compressionLevel: mixed

enableGlobalCache: true

nmHoistingLimits: dependencies

nodeLinker: node-modules

plugins:
  - checksum: 1a954a97cfa4abd6a3bf4644c11b31abdaec1e9156944e625d373e3d1a8f61a13ad9697b1a76f3affcd057667c75b2b213d4f8a8d7586c8499983b1b7f4d79a6
    path: .yarn/plugins/yarn-plugin-env-vars.cjs
    spec: "https://github.com/scinos/yarn-plugin-env-vars/releases/latest/download/yarn-plugin-env-vars.js"
  - checksum: 67ce9e30cf152af35d3dc292f915cb39220942f5f406211801da2b721d873857f8ea6d9c57893e1295133f5d128fa6388bf16a4610ef788f30e987e58f84db26
    path: .yarn/plugins/@yarnpkg/plugin-postinstall-dev.cjs
    spec: "https://raw.githubusercontent.com/sachinraja/yarn-plugin-postinstall-dev/main/bundles/%40yarnpkg/plugin-postinstall-dev.js"
