import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { dir } from 'i18next'
import './globals.css'
import { Providers } from './providers'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export type RootLayoutProps = {
  children: React.ReactNode,
  params: {
    lng: string
  }
}

export default function RootLayout({
  children,
  params
}: RootLayoutProps) {
  return (
    <html  lang={params.lng} dir={dir(params.lng)}>
      <body className={inter.className}>
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
