import type { Metadata } from "next";
import './globals.css';

import { Inter } from 'next/font/google';
import { redirect } from 'next/navigation';

import { defaultLocale, Locales, locales } from '@/i18n/i18n';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import { ThemeProvider } from '@mui/material/styles';

import { lightTheme } from '../../theme/LightTheme';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export type RootLayoutProps = Readonly<{
  children: React.ReactNode
  params: {
    locale: Locales
  }
}>;

export default function RootLayout({
  children,
  params
}: RootLayoutProps) {
  if(!locales.includes(params.locale as any)) redirect(`/${defaultLocale}`);
 return (
    <html lang="en">
      <body className={inter.className}>
        <AppRouterCacheProvider options={{}}>
          <ThemeProvider theme={lightTheme}>  
            {children}
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
